version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
      - MYSQL_ROOT_HOST= %
    volumes:
      - ./data:/var/lib/mysql
      
  catalogservice:
    image: mm/ecom-catalogs
    container_name: "ecom-catalogs"
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb